services:
  api-upload-ods-simpatika:
    image: api-upload-ods-simpatika
    cpu_percent: 10
    mem_limit: 1024M
    mem_reservation: 512M
    restart: always
    ports:
      - "8082:8080"
    networks:
      - karavan